extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  # Common typos or mis-spellings
  clickhouse: ClickHouse
  flick: Flink
  influx: InfluxDB
  kakfa: Kafka
  multicloud: multi-cloud
  postgesql: PostgreSQL
  postgres: PostgreSQL
  timeseries: time series
  "OpenSearch dashboards": "OpenSearch Dashboards"
  #
  # Apache Kafka MirrorMaker 2
  # MirrorMaker should always be followed by one (white)space character and a 2
  'MirrorMaker(?!\s+2)': "MirrorMaker 2"
  "MirrorMaker2": "MirrorMaker 2"
  # And a registered mark doesn't belong in the middle
  "Kafka® MirrorMaker 2": "Kafka MirrorMaker2"
  #
  # Aiven for <thing>
  "Aiven Cassandra": "Aiven for Cassandra"
  "Aiven ClickHouse": "Aiven for ClickHouse"
  "Aiven Elasticsearch": "Aiven for Elasticsearch"
  "Aiven Flink": "Aiven for Apache Flink"
  "Aiven Grafana": "Aiven for Grafana"
  "Aiven InfluxDB": "Aiven for InfluxDB"
  "Aiven Kafka": "Aiven for Apache Kafka"
  "Aiven M3": "Aiven for M3"
  "Aiven MySQL": "Aiven for MySQL"
  "Aiven OpenSearch": "Aiven for OpenSearch"
  "Aiven PostgreSQL": "Aiven for PostgreSQL"
  "Aiven Redis": "Aiven for Redis"
  'Aiven Kafka MirrorMaker': 'Aiven for Apache Kafka MirrorMaker 2'
  'Aiven Apache Kafka MirrorMaker': 'Aiven for Apache Kafka MirrorMaker 2'
  'Aiven for Kafka MirrorMaker': 'Aiven for Apache Kafka MirrorMaker 2'
  #
  # "Registered" marks - this section is experimental and incomplete
  #
  # Since `®` is not a "letter", the `observed` term "Kafka" will happily
  # match both "Kafka" (no `®`) and "Kafka®".
  # We need to do negative lookahead to check that the `®` is missing
  # after the word.
  "Flink(?!®)": "Flink®"
  "Kafka(?!®)": "Kafka®"
  "MirrorMaker 2(?!®)": "MirrorMaker 2®"
